[package]
name = "simple-rust-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = {version = "1.0.197", features = ["derive"]}
diesel = { version = "2.2.0", features = ["postgres"] }
